# Use the Ubuntu base image
FROM ubuntu:latest

# Set environment variables
ENV POSTGRES_USER postgres
ENV POSTGRES_PASSWORD postgres
ENV POSTGRES_DB mydatabase
ARG DEBIAN_FRONTEND=noninteractive

# Install PostgreSQL and dependencies
RUN apt-get update && \
    apt-get install -y postgresql postgresql-contrib

# Install build tools and dependencies
RUN apt-get install -y build-essential git cmake

# Clone and build pgvector
RUN apt-get install -y git
RUN git clone https://github.com/pgvector/pgvector.git && \
    cd pgvector && \
    cmake . && \
    make && \
    make install

# Initialize the PostgreSQL database
RUN service postgresql start && \
    sudo -u postgres psql -c "CREATE EXTENSION pg_vector"

# Start the PostgreSQL service
CMD ["postgres"]

# Expose the default PostgreSQL port
EXPOSE 5432

